def __pct_to_px(percent: float, dimension: int) -> int:
    """Convert a percentage (0–100) to pixels based on a screen dimension."""
    return round((percent / 100) * dimension)


WIDTH = 1280
HEIGHT = 720
FPS = 60
FOOTER_HEIGHT = __pct_to_px(10, HEIGHT)
TACHOMETER_HEIGHT = __pct_to_px(20, HEIGHT)
SHIFT_INDICATOR_HEIGHT = __pct_to_px(10, HEIGHT)
DIVIDER_WIDTH = 2
SPACING = 4
COLUMN_WIDTH = WIDTH // 4
SPEED_HEIGHT = __pct_to_px(15, HEIGHT)
CONTENT_Y = TACHOMETER_HEIGHT + SHIFT_INDICATOR_HEIGHT
BOOST_HEIGHT = __pct_to_px(15, HEIGHT)
CENTERED_CONTENT_Y = CONTENT_Y + (HEIGHT - FOOTER_HEIGHT - CONTENT_Y - 3 * __pct_to_px(15, HEIGHT)) // 2
BOOST_Y = CENTERED_CONTENT_Y + SPEED_HEIGHT
OIL_PRESSURE_HEIGHT = __pct_to_px(15, HEIGHT)
OIL_PRESSURE_Y = BOOST_Y + BOOST_HEIGHT
INTAKE_AIR_TEMP_HEIGHT = __pct_to_px(15, HEIGHT)
COOLANT_TEMP_HEIGHT = __pct_to_px(15, HEIGHT)
COOLANT_TEMP_Y = CENTERED_CONTENT_Y + INTAKE_AIR_TEMP_HEIGHT
OIL_TEMP_HEIGHT = __pct_to_px(15, HEIGHT)
OIL_TEMP_Y = COOLANT_TEMP_Y + COOLANT_TEMP_HEIGHT
AFR_HEIGHT = __pct_to_px(15, HEIGHT)
AFR_Y = CENTERED_CONTENT_Y
FUEL_LEVEL_HEIGHT = __pct_to_px(15, HEIGHT)
FUEL_LEVEL_Y = AFR_Y + AFR_HEIGHT
MILEAGE_HEIGHT = __pct_to_px(15, HEIGHT)
MILEAGE_Y = FUEL_LEVEL_Y + FUEL_LEVEL_HEIGHT
